const profile = {
  memberSince: 'Member Since',
  accountInformation: 'Account Information',
  profileInformation: 'Profile Information',
  firstName: 'First Name',
  lastName: 'Last Name',
  namedInsured: 'Named Insured',
  namedInsuredTip: 'The Named Insured is the person or business in whose name the insurance policy is issued.  In most cases, the business will be the named insured.  In terms of coverage, Named Insureds have the broadest protection and indemnity under the policy. The named insured will be in charge of choosing coverage types and amounts, will receive all policy notices, including any notices of cancellation, and will assume responsibility for payment of premiums.',
  contactName: 'Contact Name',
  change: 'Change',
  lastChanged: 'Last Changed',
  deleteAccount: 'If you are no longer interested in using Drone Insurance account you can delete them here.',
  deleteAccountAlert: 'To delete your Account, you must cancel all of your active coverages, and if you have any pending financial transactions, you will still be responsible for those charges.',
  alternativeAddress: '<strong>Alternate Address:</strong>',
  dialog: {
    changeNameTitle: 'Change Contact Name',
    changeNameParagraph: 'Changes to your name will be reflected across your Drone Insurance Account.',
    changeEmailTitle: 'Change Email',
    changeEmailParagraph: 'Please enter your email below, agree to the Consent to Electronic Delivery and apply your signature. We will be sending you a verification email.',
    newEmailAddress: 'New Email Address',
    changeEmailConsent: 'I have reviewed the <a href="%{url}" rel="noopener noreferrer" target="_blank">Consent to Electronic Delivery</a>, and understand and agree to the application of my eSignature to this document.',
    changeEmailVerificationTitle: 'Please check your email',
    changeEmailVerificationParagraph: 'Enter the verification code we sent to %{email}<br /> Your account email will only change after the email is verified.',
    changeEmailVerificationCheckSpam: 'Didn\'t receive the code?<br />Check spam or bulk folders for a message coming <br />from: account-noreply@droneinsurance.com',
    changeEmailVerificationMessage: 'Looks like you haven’t entered verification code we’ve sent to %{email}.',
    changeEmailVerificationResend: 'Resend code',
    changeEmailVerificationOr: 'or',
    changeEmailVerificationVerify: 'Verify email',
    confirmEmailPassword: 'Confirm Password to Continue',
    changePasswordTitle: 'Change Password',
    changePasswordParagraph: 'Choose a strong password and don\'t reuse it for other accounts.',
    currentPassword: 'Current Password',
    changePasswordCreateNewPassword: 'Create a new Password',
    changePasswordConfirmPassword: 'Confirm your new Password',
    deleteTitle: 'Delete Account',
    deleteParagraph: 'Are you sure you want to delete your account?<br /> If you do so, youll no longer be able to use DroneInsurance.com, and your account and its data will be lost.',
    deleteWhy: 'Tell us why you\'re closing your account:',
    deleteOptionDuplicate: 'I have a duplicate account',
    deleteOptionPrivacy: 'I have a privacy concern',
    deleteOptionNoNeed: 'I do not need it anymore',
    feedback: 'Your feedback matters. Is there anything else you\'d like us to know?',
  },
  viewCoverages: 'View your Coverages',
};

export default profile;
