const cart = {
  common: {
    purchase: 'Purchase',
    subtotal: 'Subtotal',
    cost: 'Cost',
    totalBilled: 'Total Billed',
    cardEndingIn: 'Ending in',
    cardExpires: 'Expires',
    cartTotal: 'Cart Total',
    currentPolicy: 'CURRENT POLICY',
    upcomingPolicy: 'UPCOMING POLICY',
    physicalDamage: 'Liability – Not in Flight & Physical Damage',
    liabilityOnly: 'Liability – Not in Flight',
    noDeduction: 'No Deductible',
    insuredValue: 'Insured Value',
    physicalDamageDesc: 'Physical Damage is subject to a deductible of 5% of the Insured Value each and every loss including Total Loss and Partial Loss',
  },
  addMoreCoverage: 'Add More Coverage',
  flightCoverage: 'Flight Coverage',
  signDocuments: 'Sign Documents',
  thankYouMessage: 'Thank you for choosing DroneInsurance.com!',
  orderOverview: 'Order Overview',
  totalBilled: 'Total Billed',
  todaysTotal: 'Today\'s TOTAL',
  billedMonthly: 'Billed Monthly',
  liabilityMedicalExpenses: 'Medical Expenses',
  liabilityLimits: 'Liability Limits',
  weAccept: 'We accept',
  includeSensorsAndEquipment: '<center>We noticed you have Sensors and Ground Equipment without coverage.</center><center>Would you like to Add Coverage now?</center>',
  certificateTip: 'Your COI (Certificate of Insurance) will be ready to download as soon as your purchase is complete.',
  continueToCart: 'Continue to Cart',
  confirmAndMakePayment: 'Confirm and Make Payment',
  confirm: 'Confirm',
  creditCardDetails: 'Credit Card Details',
  editPaymentMethod: 'Edit Payment Method',
  insuranceContract: 'This insurance contract is with an insurer not licensed to transact insurance in this state and is issued and delivered as surplus line coverage under the Texas insurance statutes. The Texas Department of Insurance does not audit the finances or review the solvency of the surplus lines insurer providing this coverage, and the insurer is not a member of the property and casualty insurance guaranty association created under Chapter 462, Insurance Code. Chapter 225, Insurance Code, requires payment of a 4.85% percent tax on gross premium.',
  liabilityBodilyInjury: 'Bodily Injury and Property Damage',
  liabilityBodilyInjuryDesc: '$1,000,000 each Aircraft/each occurrence',
  liabilityMedicalExpensesDesc: '$5,000 any one person',
  liabilityPersonalInjury: 'Personal & Advertising Injury',
  liabilityPersonalInjuryDesc: '$1,000,000 each Aircraft/each occurrence and in the annual aggregate',
  perilsLimitedLiability: 'War, Hi-Jacking and Other Perils Limited Liability Write-Back',
  premisesLiabilityExtension: 'Premises Liability Extension',
  prorated: 'Prorated %{numDays} of %{daysInMonth} days',
  shortRateCancellationTerms: 'Short Rate Cancellation Terms',
  shortRateCancellationTermsParagraph: 'If you cancel this Flight Coverage on or after 12:01am of its effective date, the amount of premium returned to you will be 40% of the unearned premium. Please review your policy for full details.',
  storePaymentMethod: 'To ensure continued service, we\'ll store your payment method',
  automaticallyRenewed: 'Coverage will automatically renew each month until cancelled',
  autoBill: 'Your card will be automatically billed each month of your policy period until cancelled.',
  autoBillSub: 'The monthly rate is pro-rated for this billing only.  Your card will be automatically billed at the full monthly rate for each subsequent month of the policy period.',
  triaLiabilityCoverage: 'TRIA Liability Coverage',
  equipmentCoverage: 'Equipment Coverage',
  previousClaims: 'Due to previous claims you are unable to purchase the policy unless you add coverage to at least %{number} drones.<br/>',
  expiredFCModal: {
    header: 'The following Scheduled Flight Coverage(s) have invalid date(s) and will be removed from the Cart',
    removeFromCart: 'Remove from Cart',
  },
  nothingInCart: 'Your do not have any coverage in your cart',
  profileNotExist: 'Your profile does not exist!',
  subCoverage: {
    liability: 'Liability',
    baseCoverage: 'Base coverage is required to add your drone to the policy. Your drone does not have any insurance coverage until base coverage is added and the payment process is completed. %{addedText}',
    baseCoverageIncludes: 'Base Liability Coverage includes the following coverages while your drone is Not in Flight',
    personalCoverage: 'Personal & Advertising Injury Coverage, limit of %{personalCoverage} each occurrence and in the annual aggregate',
    premisesCoverage: 'Premises Liability Coverage, limit of %{premisesCoverage} each occurrence',
    injuryAndPropertyCoverage: '3rd-party Bodily Injury and Property Damage Liability Coverage, limit of %{propertyCoverage} each aircraft/each occurrence',
    medicalCoverage: 'Medical Payments to Others Coverage, limit of %{medicalCoverage} per person / per occurrence',
    worldWideCoverage: 'Worldwide coverage territory',
    terrorismAndWarCoverage: 'Terrorism and War Risk (Hijacking) Coverage, limit of %{hijackingCoverage} each occurrence',
    emptyAssetMsg: 'You do not have any %{coverageType}.',
  },
  paymentDeferred: 'This amount won\'t be processed at this time. It will be charged with your next bill.',
  thisAmount: 'This amount from ',
  notCharged: 'is now being charged',
  totalToPay: 'Total to Pay',
  completed: {
    title: 'Order Complete!',
    invoice: 'Invoice',
    downloadPDF: 'Download PDF',
    downloading: 'Downloading',
    policyDocument: 'Policy Documents',
    insuranceCertificate: 'Certificate of Insurance',
    additionalInsured: 'Additional Insured',
    add: 'Add',
    selectAndDownload: 'Select and Download',
    printUnavailable: 'Not available for print',
    downloadFailed: 'Failed to download document.',
  },
};

export default cart;
