const coverage = {
  hide: 'Hide',
  equalPayments: '12 equal payments of ',
  dueDateFor12Months: 'Due the %{dueDate} of each month for the next 11/12  months',
  hideCoverage: 'Hide Coverage',
  hullCoverage: 'Hull Coverage',
  hullCoverageLC: 'hull coverage',
  itemInCart: 'Item in Cart',
  looksNoCoverage: 'It looks like you don\'t have coverage yet.',
  noInsuranceCoverage: 'No Insurance Coverage',
  noCoverage: 'No Coverage',
  noEquipmentCoverage: 'It seems you haven’t added any ground equipment yet',
  noScheduleFlightCoverage: 'No Scheduled Flight Coverage',
  noSensorCoverage: 'It seems you haven’t added any sensors yet',
  physicalDamageCoverage: 'Physical Damage Coverage',
  removeCoverage: 'Remove Coverage',
  saveMore: 'Lower pricing when adding more. Save more when you add more.',
  scheduledFlightCoverage: 'Scheduled Flight Coverage',
  scheduleFlightCoverage: 'Schedule Flight Coverage',
  requiredAtLeastOneDroneMsg: 'You must add coverage to at least one Drone to the Cart before adding coverage to your %{type}.',
  insuredValue: 'Insured Value',
  showCoverage: 'Show Coverage',
  usage: 'Usage',
  coverageOverview: 'Coverage Overview',
  coverageSummary: 'Coverage Summary',
  coverageTnc: '*All coverage is subject to policy terms and conditions.',
  covered: 'Covered',
  notSelected: 'Not Selected',
  flightCoverageNotSetup: 'You have not set up your flight coverage correctly - Please make sure the liability amount, drones usages and schedule are selected.',
  needCoverage: 'It looks like you don\'t have any coverage yet. Add coverage to at least one drone to have your Policy set up.',
  back: 'Back to Coverage Overview',
  paymentCycleInfo: 'Due the %{billDate} of each month for the<br />next 11 to 12 months',
  activePolicy: 'Active Policy',
  activeSince: 'Active Since',
  addCoverage: 'Add Coverage',
  removeCancelCoverage: 'Remove and Cancel Coverage',
  addEquipment: 'Add Equipment',
  baseCoverageRolloverMessage: 'Base Coverage for your new drone will be active for the remainder of your current policy, and will automatically rollover to your upcoming policy. You can cancel Base Coverage at any time.',
  upcomingPolicy: '<b>Upcoming Policy</b>',
  currentPolicy: '<b>Current Policy</b>',
  addSensor: 'Add Sensor',
  addCoveragetoCart: 'Add Coverage to Cart',
  addedToCart: 'Added to Cart',
  checkout: 'Checkout',
  addCoverageToDrone: 'Add Coverage to a Drone below to set up your policy',
  added: 'Added',
  addEasyCoverage: 'Adding coverage is quick and easy.',
  addHullCoverage: 'Add hull coverage',
  addPhysicalDamageCoverage: 'Add Physical Damage Coverage',
  clickAddCoverage: 'Click Add Coverage below.',
  additionalInsuredName: 'Individual or Corporation name',
  includeAdditionalInsured: 'You can include Additional Insured',
  additionalInsured: 'Additional Insured',
  dueAtPolicyRenewal: 'Due at Policy Renewal',
  liabilityOnly: 'Liability Only',
  physicalDamageSubscription: 'Liability & Physical Damage Coverage',
  physicalDamageLiability: 'Liability & Physical Damage',
  liabilitySubscription: 'Liability Only',
  claimsHistory: 'Due to previous claims you won’t be able to create your policy unless you add coverage to at least %{number} drones.',
  failed: {
    fetchingFCRefundPricing: 'Failed to fetch refund price for this flight coverage',
    creditCardUpdate: 'Failed to update credit card',
    fCCancellation: 'Failed to cancel flight coverage',
    sensorCoverageCancellation: 'Failed to cancel sensor coverage',
    groundEquipCoverageCancellation: 'Failed to cancel ground equipment coverage',
  },
  extendedEndDate: 'Selected Flight Coverage goes through the current and the upcoming policy.  In your cart you will see separate bills for this Flight Coverage – one for the portion of the Flight Coverage period occurring during the current policy and one for the portion of the Flight Coverage period occurring during your upcoming policy.',
  baseCoverageForm: {
    dontNeed: 'I don\'t need',
    fivePercentDeductible: '5% Deductible on Total or Partial Losses',
    physicalDamageIncludes: 'Physical Damage Coverage includes',
    physicalDamageInFlight: 'Physical Damage Coverage for your drone while your drone is in Flight<br />*Flight Coverage must be added',
    physicalDamageNotFlight: 'Physical Damage and Theft Coverage while your drone is Not in Flight',
    theftNotInFlight: 'Theft coverage while your drone is Not in flight (must be missing for 30 days)',
    priceToolTip: '12 equal payments.',
    theftLossMessage: 'Theft Coverage: Where any Unmanned Aircraft System (or any part thereof) scheduled under this Policy has been unlawfully and wrongfully taken during the policy period by an unknown person or persons without Your knowledge and consent (and without the knowledge and consent of any injured), and the Unmanned Aircraft System (or any part thereof) is not recovered within 30 days of such an event.',

  },
  flightCoverageForm: {
    flightCoverageIncludes: 'Flight Coverage includes',
    header: 'Set your Flight Coverage Liability amount',
    iWillDoIt: 'I will do it',
    later: 'later',
    notSeeing: 'Not seeing what you need?',
    oneDayoneYearPeriod: 'Schedule Flight Coverage for as short as one day and up to one year',
    pleaseSelect: 'Please select all that apply.',
    fcNewJobComingUp: 'Have a job coming up?<br />You can schedule Flight Coverage now and it will automatically kick in on the day you choose.',
    policy: 'Policy',
    scheduledYourFlightCoverage: 'Schedule your Flight Coverage',
    scheduleYour: 'Schedule Your',
    talkToUs: 'Talk to us',
    thirdPartyPropertyInFlight: '3rd-party Bodily Injury and Property Damage Liability Coverage while your drone is in Flight',
    twoFiveMillionFlightLiability: 'Liability Limits up to $25 million',
    viewFlightEndorsement: 'View a sample Flight Coverage endorsement',
    intendedDroneUsage: 'What do you plan to use this drone for?',
  },
  common: {
    addFlightCoverage: 'Add Flight Coverage',
    editFlightCoverage: 'Edit Flight Coverage',
    addToCart: 'Add to Cart',
    submit: 'Submit',
    continue: 'Continue',
    estimatedCost: 'Estimated cost',
    liabilityCoverageAmount: 'Flight Coverage Liability Limit',
    selectedDrones: 'Selected Drones',
    viewSamplePolicy: 'View a sample policy',
    setupYourPolicy: 'Set Up Your Policy',
    haveNoCreditCard: 'You have no credit cards.',
    noCreditCardFound: 'No credit card found.',
    showCoverageDetails: 'Show Coverage Details',
    hideCoverageDetails: 'Hide Coverage Details',
    viewFile: 'View File',
    tipSection: {
      watchVideo: 'Watch Video',
      heading: 'How to add an Additional Insured?',
      followSteps: 'After purchasing Flight Coverage, you can easily add an Additional Insured with just a few keystrokes. Please follow the steps below.',
      coverageOverview: 'Under the “Coverage” tab click on the “Add Additional Insured”.',
      certificateInsurance: 'Select the “Certificate of Insurance” tab. Under chosen Flight Coverage Certificate, click on the “Select Certificate(s) of Insurance”.',
      addAditionalInsured: 'Click “Add Additional Insured,” fill the form, save, and you are all set.',
      tip: 'Tip:',
      tipAditionalInsured: 'Learn how to add an Additional Insured',
    },
  },
  dialog: {
    cancelCoverageAsset: 'Are you sure you want to remove this %{asset} and cancel coverage?',
    cancelCoverageWarning: 'WARNING: By canceling this coverage you acknowledge that this %{asset} will lose all coverage under this insurance policy effective immediately, and you are voluntarily renouncing your right to file a claim for any known or unknown incidents that may have happened while this %{asset} was insured under this policy.',
    remove: 'Are you sure you want to remove this %{asset} from DroneInsurance.com?',
  },
  eSignatureForm: {
    acknowledge: 'Please acknowledge the document(s) and apply your signature(s) to set up your policy.',
    applySignature: 'Apply Signature',
    applySignatureButton: 'Review Next Document',
    cannotLoadDocument: 'Sorry, we cannot load this document.',
    coverNote: 'Cover Note',
    consentElectronicDelivery: 'Consent to Electronic Delivery',
    coverNoteTitle: 'The placeholders in the above from Cover Note will be replaced with the information below.',
    coverNoteContent: 'The Policy Number will be generated and supplied upon purchase.',
    amountsReflected: 'Amounts reflect a full policy year. Any Flight Coverage premiums are not displayed.',
    consentDeliveryTitle: 'The placeholder in the above Consent to Electronic Delivery will be replaced with the email address below',
    esignAcknowledgment: 'I acknowledge and agree that I have read and understand the %{tnc}. Further, I have reviewed the Cover Note and Consent to Electronic Delivery above, and understand and agree to the application of my eSignature to these documents.',
    esignAcknowledgmentTNC: 'Point of Sale Terms and Conditions',
    eSignatureCompleteSettings: 'To complete your order and create your policy, we require an e-signature to be placed on Insurance Documents.',
    eSignatureTooltip: 'Type your name below. By clicking \'Apply Signature\', you will electronically sign the document(s)',
    signature: 'Signature',
    signedDocuments: 'Signed Documents',
    viewFullPolicyDetails: 'View Full Policy Details | Other Documents',
    viewHere: 'You can view it here.',
    insuredsName: 'Insured\'s Name: %{name} <br />',
    insuredsEmail: 'Insured\'s Email: %{email} <br />',
    insuredsAddress: 'Insured\'s Address: %{address} <br />',
    policyPeriod: 'Policy Period: %{policyPeriod} <br />',
    liabilityPremium: 'Liability Premium: %{liabilityPremium} ',
    totalPremium: 'Total Premium: %{totalPremium} <br />',
    totalTax: 'Total: %{totalTax} ',
    physicalDamagePremium: 'Physical Damage Premium: %{physicalDamagePremium} ',
  },
  pilotsForm: {
    requiredAtLeastOnePilotMsg: '*Your policy requires at least one active Pilot',
    confirmYourPilot: 'Confirm your Pilots',
  },
  viewFlightCoverage: {
    cancelFlightCoverage: 'Cancel This Flight Coverage',
    coverageInfoNote: 'The scheduled flight coverage is active and cannot be edited at this time.',
    coverageInfoTitle1: 'Need to increase your Flight Liability amount?',
    coverageInfoTitle2: 'Need to decrease your Flight Liability amount?',
    coverageInfoSubtitle1: 'Easily increase the Flight Liability amount for this date range by scheduling a new Flight Coverage and selecting the increased amount.',
    coverageInfoSubtitle2: 'The Flight Coverage liability limit cannot be decreased without cancelling the active Flight Coverage. Please note, canceled active Flight Coverage will be subject to a Minimum Earner Premium charge of 40%.',
    coverageLiabilityAmount: 'Flight Coverage Liability Amount',
    coveredDrone: 'Covered Drones',
    droneUsage: 'Drone Usage',
  },
};

export default coverage;
